const SecretKeys = {
  BASE_URL: 'BASE_URL',
  PROJECT_NAME: 'PROJECT_NAME',
  MONGO_URI: 'MONGO_URI',
  JWT_SECRET: 'JWT_SECRET',
  JWT_SECRET_ONETIME: 'JWT_SECRET_ONETIME',
  VENDOR_MAILJET_KEY: 'VENDOR_MAILJET_KEY',
  VENDOR_MAILJET_SECRET: 'VENDOR_MAILJET_SECRET',
  VENDOR_MAILJET_EMAIL: 'VENDOR_MAILJET_EMAIL',
  VENDOR_MAILJET_EMAIL_NAME: 'VENDOR_MAILJET_EMAIL_NAME',
  VENDOR_MAILJET_SEND_FORGOT_PASSWORD_OTP_TEMPLATE_ID:
    'VENDOR_MAILJET_SEND_FORGOT_PASSWORD_OTP_TEMPLATE_ID',
};

export default SecretKeys;
